### PR TITLE
Show select list for crete command

### PR DESCRIPTION
**Pull request by WSMathias**
Screenshot 2020-07-27 at 10 29 51 AM
Screenshot 2020-07-27 at 11 15 22 AM
Screenshot 2020-07-27 at 9 53 40 PM

### CODE REVIEW

**Comment by mountain-nerd** [comment]
This is a nice feature :+1:

**Comment by vs4vijay** [comment]
Hey @WSMathias , If you specify exact starterkit using `--starterkit`, will vega still show the survey prompt?

**Comment by vs4vijay** [comment]
If possible, then you can try to reuse the code: https://github.com/srijanone/vega/blob/develop/cmd/install.go#L49

**Comment by WSMathias** [comment]
@vs4vijay  No, it won't show prompt for exact match and a single match.

**Pull request merged**
